In [4]:
import numpy as np

In [8]:
n = np.array([1,2,3])

In [10]:
n * n

array([1, 4, 9])

In [11]:
n + n

array([2, 4, 6])

In [12]:
np.sqrt(n)

array([ 1.        ,  1.41421356,  1.73205081])

In [13]:
np.log(n)

array([ 0.        ,  0.69314718,  1.09861229])

In [14]:
m = np.array([[1,2],[3,4]])

In [16]:
m

array([[1, 2],
       [3, 4]])

In [19]:
np.linalg.norm(m)

5.4772255750516612

In [23]:
np.dot(m,m)

array([[ 7, 10],
       [15, 22]])